### ISSUE TITLE
package.json default packages & qol scripts

### ISSUE THREAD

**Issue by zoe-codez** [Digital-Alchemy-TS/docker-standalone#9]
### Update libraries command

Could use a command to upgrade the @digital-alchemy libraries, then rebuild type definitions. 

Using https://www.npmjs.com/package/npm-check-updates - 
```bash
ncu -f @digital-alchemy -u
# install
# rebuild types
```
### Update types

A simple alias of `type-writer` to a package.json script, in order to aid discoverability. Will cause the command to surface more easily in editors and such

### Add dayjs by default

https://www.npmjs.com/package/dayjs

It's used by the internals / docs as the preferred tool for date based math

### default version

Can this be 0.3.0 instead, matching the current `0.3.x` compatibility version used in the rest of the repos

**Comment by webbertakken** [comment]
Re: `Update libraries` and `Update types`

I packaged them both in the same file, which runs quickly enough to always be used as a single script.

https://github.com/Digital-Alchemy-TS/automation-standalone/pull/10/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R10

Re: `Add dayjs by default`

Added
